sbcl: Filter out invalid definition sources in find-definitions
They can't be visited, so filtering them eliminates this error:

    Error: DEFINITION-SOURCE of blah did not contain meaningful
    information

* slynk/backend/sbcl.lisp (categorize-definition-source): Move up.
(find-definitions) Use it.

This commonly arises when a method is defined without a corresponding
defgeneric.

Cherry-picked-from: SLIME commit 8c758ba4aae8cccc8a4575e9b3f83cd42b0f5586
Co-authored-by: João Távora <joaotavora@gmail.com>